# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from partna_python_sdk import Partna

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        partna = Partna(
        
                        admin_secret = 'YOUR_API_KEY',
        
                        api_key = 'YOUR_API_KEY',
        
                        api_user = 'YOUR_API_KEY',
        
                        user_version = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(partna)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
