# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import partna_python_sdk
from partna_python_sdk.paths.v1_mock_payment import post
from partna_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1MockPayment(ApiTestMixin, unittest.TestCase):
    """
    V1MockPayment unit test stubs
        Make a mock payment
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
