# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.currency_list_supported_currencies_response import CurrencyListSupportedCurrenciesResponse
from partna_python_sdk import configuration


class TestCurrencyListSupportedCurrenciesResponse(unittest.TestCase):
    """CurrencyListSupportedCurrenciesResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
