# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.balance_get_account_balance200_response_data import BalanceGetAccountBalance200ResponseData
from partna_python_sdk import configuration


class TestBalanceGetAccountBalance200ResponseData(unittest.TestCase):
    """BalanceGetAccountBalance200ResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
