# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.payment_create_new_payment_response import PaymentCreateNewPaymentResponse
from partna_python_sdk import configuration


class TestPaymentCreateNewPaymentResponse(unittest.TestCase):
    """PaymentCreateNewPaymentResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
