# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.voucher_redeem_and_withdraw404_response_errors import VoucherRedeemAndWithdraw404ResponseErrors
from partna_python_sdk import configuration


class TestVoucherRedeemAndWithdraw404ResponseErrors(unittest.TestCase):
    """VoucherRedeemAndWithdraw404ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
