# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.transaction_get_details_response import TransactionGetDetailsResponse
from partna_python_sdk import configuration


class TestTransactionGetDetailsResponse(unittest.TestCase):
    """TransactionGetDetailsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
