# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.rates_get_current_rates_response_data_your_currency import RatesGetCurrentRatesResponseDataYourCurrency
from partna_python_sdk import configuration


class TestRatesGetCurrentRatesResponseDataYourCurrency(unittest.TestCase):
    """RatesGetCurrentRatesResponseDataYourCurrency unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
