# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.bank_account_verify_and_return_details_response import BankAccountVerifyAndReturnDetailsResponse
from partna_python_sdk import configuration


class TestBankAccountVerifyAndReturnDetailsResponse(unittest.TestCase):
    """BankAccountVerifyAndReturnDetailsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
