# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.voucher_get_multiple_records_response_data_item import VoucherGetMultipleRecordsResponseDataItem
from partna_python_sdk import configuration


class TestVoucherGetMultipleRecordsResponseDataItem(unittest.TestCase):
    """VoucherGetMultipleRecordsResponseDataItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
