# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import partna_python_sdk
from partna_python_sdk.model.voucher_redeem_existing_unused_response_data import VoucherRedeemExistingUnusedResponseData
from partna_python_sdk import configuration


class TestVoucherRedeemExistingUnusedResponseData(unittest.TestCase):
    """VoucherRedeemExistingUnusedResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
