# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.api_key_generate_new_api_key_response_data import ApiKeyGenerateNewApiKeyResponseData

class RequiredApiKeyGenerateNewApiKeyResponse(TypedDict):
    pass

class OptionalApiKeyGenerateNewApiKeyResponse(TypedDict, total=False):
    data: ApiKeyGenerateNewApiKeyResponseData

class ApiKeyGenerateNewApiKeyResponse(RequiredApiKeyGenerateNewApiKeyResponse, OptionalApiKeyGenerateNewApiKeyResponse):
    pass
