# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBalanceWithdrawFundsRequest(TypedDict):
    # The account name. This is the name of the account holder.
    accountName: str

    # The account number of the user's bank account.
    accountNumber: str

    # The amount to be withdrawn.
    amount: str

    # The bank name. e.g. \"Access Bank\".
    bank: str

    # The bank code. e.g. \"044\".
    bankCode: str

    # The currency of the withdrawal.
    currency: str

    # The type of OTP to be used.
    otpType: str

class OptionalBalanceWithdrawFundsRequest(TypedDict, total=False):
    # The token to be used for OTP.
    token: str

class BalanceWithdrawFundsRequest(RequiredBalanceWithdrawFundsRequest, OptionalBalanceWithdrawFundsRequest):
    pass
