# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBalanceTransferFundsRequest(TypedDict):
    # Currency being sent.
    currency: str

    # Receiver's coinprofile username.
    receiverUsername: str

class OptionalBalanceTransferFundsRequest(TypedDict, total=False):
    # Amount to transfer.
    amount: str

    # Transaction memo.
    memo: str

    # The type of OTP to be used.
    otpType: str

    # The token to be used for OTP.
    token: str

class BalanceTransferFundsRequest(RequiredBalanceTransferFundsRequest, OptionalBalanceTransferFundsRequest):
    pass
