# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.balance_get_account_balance_response_data import BalanceGetAccountBalanceResponseData

class RequiredBalanceGetAccountBalanceResponse(TypedDict):
    pass

class OptionalBalanceGetAccountBalanceResponse(TypedDict, total=False):
    data: BalanceGetAccountBalanceResponseData

    message: str

    success: bool

class BalanceGetAccountBalanceResponse(RequiredBalanceGetAccountBalanceResponse, OptionalBalanceGetAccountBalanceResponse):
    pass
