# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBalanceGetAccountBalance200ResponseDataBalances(TypedDict):
    pass

class OptionalBalanceGetAccountBalance200ResponseDataBalances(TypedDict, total=False):
    # User's balance amount
    amount: int

    formattedAmount: int

    toCurrency: str

    totalRecieved: int

    totalSent: int

    txnCount: typing.Union[int, float]

class BalanceGetAccountBalance200ResponseDataBalances(RequiredBalanceGetAccountBalance200ResponseDataBalances, OptionalBalanceGetAccountBalance200ResponseDataBalances):
    pass
