# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBalanceTransferFundsResponseData(TypedDict):
    pass

class OptionalBalanceTransferFundsResponseData(TypedDict, total=False):
    amount: str

    date: date

    fromCurrency: str

    receiveAmount: str

    sender: str

    senderPrevbalance: str

    status: str

    toCurrency: str

    transactionId: str

    username: str

class BalanceTransferFundsResponseData(RequiredBalanceTransferFundsResponseData, OptionalBalanceTransferFundsResponseData):
    pass
