# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.balance_transfer_funds_response_data import BalanceTransferFundsResponseData

class RequiredBalanceTransferFundsResponse(TypedDict):
    pass

class OptionalBalanceTransferFundsResponse(TypedDict, total=False):
    data: BalanceTransferFundsResponseData

    message: str

    success: bool

class BalanceTransferFundsResponse(RequiredBalanceTransferFundsResponse, OptionalBalanceTransferFundsResponse):
    pass
