# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBankAccountVerifyAndReturnDetailsRequest(TypedDict):
    # The account number.
    accountNumber: str

    # The bank code.
    bankCode: str

class OptionalBankAccountVerifyAndReturnDetailsRequest(TypedDict, total=False):
    pass

class BankAccountVerifyAndReturnDetailsRequest(RequiredBankAccountVerifyAndReturnDetailsRequest, OptionalBankAccountVerifyAndReturnDetailsRequest):
    pass
