# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBankAccountVerifyAndReturnDetailsResponseData(TypedDict):
    pass

class OptionalBankAccountVerifyAndReturnDetailsResponseData(TypedDict, total=False):
    accountname: str

    accountnumber: str

    code: str

    country: str

    created_at: str

    currency: str

    deleted_at: str

    internalreference: str

    is_trashed: str

    is_visible: str

    name: str

    phonenumber: str

    responsecode: str

    responsemessage: str

    uniquereference: str

    updated_at: str

class BankAccountVerifyAndReturnDetailsResponseData(RequiredBankAccountVerifyAndReturnDetailsResponseData, OptionalBankAccountVerifyAndReturnDetailsResponseData):
    pass
