# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.currency_list_supported_currencies_response_data import CurrencyListSupportedCurrenciesResponseData

class RequiredCurrencyListSupportedCurrenciesResponse(TypedDict):
    pass

class OptionalCurrencyListSupportedCurrenciesResponse(TypedDict, total=False):
    data: CurrencyListSupportedCurrenciesResponseData

class CurrencyListSupportedCurrenciesResponse(RequiredCurrencyListSupportedCurrenciesResponse, OptionalCurrencyListSupportedCurrenciesResponse):
    pass
