# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantsUpdateRecordRequest(TypedDict):
    pass

class OptionalMerchantsUpdateRecordRequest(TypedDict, total=False):
    # Merchant callback URL. Webhook will be sent to this URL.
    callbackUrl: str

    # Merchants can set this property to their desired currency. Their balance on Ventogram will be credited with this currency when their users redeem voucher created on Ventogram. Conversion between different currencies will be performed at the rate which is obtainable at the time of redeeming the voucher. If this is not set by the merchant,  their balance will be credited with the currency used in creating the voucher.
    creditCurrency: str

    # Bearer of the voucher fee
    feeBearer: str

    # Merchant logo URL
    logo: str

class MerchantsUpdateRecordRequest(RequiredMerchantsUpdateRecordRequest, OptionalMerchantsUpdateRecordRequest):
    pass
