# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantsGetRecordResponseData(TypedDict):
    pass

class OptionalMerchantsGetRecordResponseData(TypedDict, total=False):
    # Merchant's credit currency
    creditCurrency: str

    # Merchant email address
    email: str

    # API key expiry date and time
    expires: datetime

    # Merchant logo URL
    logo: str

    # Merchant username
    username: str

class MerchantsGetRecordResponseData(RequiredMerchantsGetRecordResponseData, OptionalMerchantsGetRecordResponseData):
    pass
