# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.merchants_get_record_response_data import MerchantsGetRecordResponseData

class RequiredMerchantsGetRecordResponse(TypedDict):
    pass

class OptionalMerchantsGetRecordResponse(TypedDict, total=False):
    data: MerchantsGetRecordResponseData

    message: str

    success: bool

class MerchantsGetRecordResponse(RequiredMerchantsGetRecordResponse, OptionalMerchantsGetRecordResponse):
    pass
