# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMerchantsUpdateRecordResponseData(TypedDict):
    pass

class OptionalMerchantsUpdateRecordResponseData(TypedDict, total=False):
    callbackUrl: str

    creditCurrency: str

    feeBearer: str

    logo: str

    username: str

class MerchantsUpdateRecordResponseData(RequiredMerchantsUpdateRecordResponseData, OptionalMerchantsUpdateRecordResponseData):
    pass
