# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.payment_create_new_payment_response_data import PaymentCreateNewPaymentResponseData

class RequiredPaymentCreateNewPaymentResponse(TypedDict):
    pass

class OptionalPaymentCreateNewPaymentResponse(TypedDict, total=False):
    data: PaymentCreateNewPaymentResponseData

    message: str

    success: bool

class PaymentCreateNewPaymentResponse(RequiredPaymentCreateNewPaymentResponse, OptionalPaymentCreateNewPaymentResponse):
    pass
