# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaymentCreateNewPaymentRequest(TypedDict):
    # The business id
    businessId: str

    # The rate key
    customerEmail: str

    # The incoming currency
    incomingCurrency: str

    # The outgoing currency
    outgoingCurrency: str

    # The payment type
    paymentType: str

class OptionalPaymentCreateNewPaymentRequest(TypedDict, total=False):
    # The account name. Required when paymentType is bank
    accountName: str

    # The account number. Required when paymentType is bank
    accountNumber: str

    # The bank name. Required when paymentType is bank
    bank: str

    # The bank code. Required when paymentType is bank
    bankCode: str

    # The coinprofile username. Required when paymentType is profile
    coinprofileUsername: str

    # The country. Required when paymentType is bank
    country: str

    # The incoming amount
    incomingAmount: typing.Union[int, float]

    # The outgoing amount
    outgoingAmount: typing.Union[int, float]

    # The rate key
    rateKey: str

    # The reference
    reference: str

class PaymentCreateNewPaymentRequest(RequiredPaymentCreateNewPaymentRequest, OptionalPaymentCreateNewPaymentRequest):
    pass
