# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPaymentCreateNewPaymentResponseData(TypedDict):
    pass

class OptionalPaymentCreateNewPaymentResponseData(TypedDict, total=False):
    _id: str

    account: str

    address: str

    businessId: str

    confirmedAmount: int

    createdAt: str

    customerEmail: str

    expTime: str

    incomingAmount: int

    incomingCurrency: str

    outgoingAmount: int

    outgoingCurrency: str

    paymentType: str

    rate: int

    reference: str

    senderUsername: str

    state: str

    threadTS: str

    unconfirmedAmount: int

    updatedAt: str

class PaymentCreateNewPaymentResponseData(RequiredPaymentCreateNewPaymentResponseData, OptionalPaymentCreateNewPaymentResponseData):
    pass
