# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.rates_get_current_rates_response_data import RatesGetCurrentRatesResponseData

class RequiredRatesGetCurrentRatesResponse(TypedDict):
    pass

class OptionalRatesGetCurrentRatesResponse(TypedDict, total=False):
    data: RatesGetCurrentRatesResponseData

class RatesGetCurrentRatesResponse(RequiredRatesGetCurrentRatesResponse, OptionalRatesGetCurrentRatesResponse):
    pass
