# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.rates_get_conversion_rates_response_data_usdngn import RatesGetConversionRatesResponseDataUsdngn

class RequiredRatesGetConversionRatesResponseData(TypedDict):
    pass

class OptionalRatesGetConversionRatesResponseData(TypedDict, total=False):
    USDNGN: RatesGetConversionRatesResponseDataUsdngn

class RatesGetConversionRatesResponseData(RequiredRatesGetConversionRatesResponseData, OptionalRatesGetConversionRatesResponseData):
    pass
