# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.rates_get_conversion_rates_response_data import RatesGetConversionRatesResponseData

class RequiredRatesGetConversionRatesResponse(TypedDict):
    pass

class OptionalRatesGetConversionRatesResponse(TypedDict, total=False):
    data: RatesGetConversionRatesResponseData

    message: str

    success: bool

class RatesGetConversionRatesResponse(RequiredRatesGetConversionRatesResponse, OptionalRatesGetConversionRatesResponse):
    pass
