# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.rates_get_current_rates_response_data_your_currency import RatesGetCurrentRatesResponseDataYourCurrency

class RequiredRatesGetCurrentRatesResponseData(TypedDict):
    pass

class OptionalRatesGetCurrentRatesResponseData(TypedDict, total=False):
    YOUR_CURRENCY: RatesGetCurrentRatesResponseDataYourCurrency

    publicKey: str

    signature: str

class RatesGetCurrentRatesResponseData(RequiredRatesGetCurrentRatesResponseData, OptionalRatesGetCurrentRatesResponseData):
    pass
