# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.transaction_get_user_transactions_response_data import TransactionGetUserTransactionsResponseData

class RequiredTransactionGetUserTransactionsResponse(TypedDict):
    pass

class OptionalTransactionGetUserTransactionsResponse(TypedDict, total=False):
    data: TransactionGetUserTransactionsResponseData

    message: str

    success: bool

class TransactionGetUserTransactionsResponse(RequiredTransactionGetUserTransactionsResponse, OptionalTransactionGetUserTransactionsResponse):
    pass
