# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTransactionsGetMerchantTransactionSummaryResponseData(TypedDict):
    pass

class OptionalTransactionsGetMerchantTransactionSummaryResponseData(TypedDict, total=False):
    # Total count of paid vouchers
    totalPaid: int

    # Total count of redeemed vouchers
    totalRedeemed: int

    # Total count of unpaid vouchers
    totalUnpaid: int

    # Total count of unredeemed vouchers
    totalUnredeemed: int

class TransactionsGetMerchantTransactionSummaryResponseData(RequiredTransactionsGetMerchantTransactionSummaryResponseData, OptionalTransactionsGetMerchantTransactionSummaryResponseData):
    pass
