# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.transactions_get_merchant_transaction_summary_response_data import TransactionsGetMerchantTransactionSummaryResponseData

class RequiredTransactionsGetMerchantTransactionSummaryResponse(TypedDict):
    pass

class OptionalTransactionsGetMerchantTransactionSummaryResponse(TypedDict, total=False):
    data: TransactionsGetMerchantTransactionSummaryResponseData

    message: str

    success: bool

class TransactionsGetMerchantTransactionSummaryResponse(RequiredTransactionsGetMerchantTransactionSummaryResponse, OptionalTransactionsGetMerchantTransactionSummaryResponse):
    pass
