# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.transaction_get_user_transaction_summary_response_data_summary import TransactionGetUserTransactionSummaryResponseDataSummary
from partna_python_sdk.type.transaction_get_user_transaction_summary_response_data_txn import TransactionGetUserTransactionSummaryResponseDataTxn

class RequiredTransactionGetUserTransactionSummaryResponseData(TypedDict):
    pass

class OptionalTransactionGetUserTransactionSummaryResponseData(TypedDict, total=False):
    summary: TransactionGetUserTransactionSummaryResponseDataSummary

    txn: TransactionGetUserTransactionSummaryResponseDataTxn

class TransactionGetUserTransactionSummaryResponseData(RequiredTransactionGetUserTransactionSummaryResponseData, OptionalTransactionGetUserTransactionSummaryResponseData):
    pass
