# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTransactionGetDetailsResponse(TypedDict):
    pass

class OptionalTransactionGetDetailsResponse(TypedDict, total=False):
    amount: typing.Union[int, float]

    businessId: str

    currency: str

    fromAmount: typing.Union[int, float]

    fromCurrency: str

    isFromRegUser: bool

    memo: str

    message: str

    prevBalance: typing.Union[int, float]

    sender: str

    status: str

    success: bool

    transactionId: str

    type: str

    username: str

class TransactionGetDetailsResponse(RequiredTransactionGetDetailsResponse, OptionalTransactionGetDetailsResponse):
    pass
