# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_get_record404_response_errors import VoucherGetRecord404ResponseErrors

class RequiredVoucherGetRecord404Response(TypedDict):
    pass

class OptionalVoucherGetRecord404Response(TypedDict, total=False):
    errors: VoucherGetRecord404ResponseErrors

    message: str

    success: bool

class VoucherGetRecord404Response(RequiredVoucherGetRecord404Response, OptionalVoucherGetRecord404Response):
    pass
