# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVoucherCreatePaymentRequest(TypedDict):
    # Required voucher amount
    amount: int

    # Required voucher currency
    currency: str

    # User email
    email: str

    # Fullname of the user creating voucher
    fullname: str

class OptionalVoucherCreatePaymentRequest(TypedDict, total=False):
    # This is a Ventogram-signed rate key. If provided when a voucher is created, the conversion will use the rate signed with this key if it is valid at the time of redeeming a voucher. Conversion will use the current rate if key has expired.
    rateKey: str

class VoucherCreatePaymentRequest(RequiredVoucherCreatePaymentRequest, OptionalVoucherCreatePaymentRequest):
    pass
