# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_minmax_amount_get_min_max_amount_response_data import VoucherMinmaxAmountGetMinMaxAmountResponseData

class RequiredVoucherMinmaxAmountGetMinMaxAmountResponse(TypedDict):
    pass

class OptionalVoucherMinmaxAmountGetMinMaxAmountResponse(TypedDict, total=False):
    data: VoucherMinmaxAmountGetMinMaxAmountResponseData

    message: str

    success: bool

class VoucherMinmaxAmountGetMinMaxAmountResponse(RequiredVoucherMinmaxAmountGetMinMaxAmountResponse, OptionalVoucherMinmaxAmountGetMinMaxAmountResponse):
    pass
