# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVoucherGetMultipleRecordsResponseDataItem(TypedDict):
    pass

class OptionalVoucherGetMultipleRecordsResponseDataItem(TypedDict, total=False):
    amount: typing.Union[int, float]

    createdAt: datetime

    currency: str

    # This is defined only if the voucher payment has been received
    dateRedeemed: datetime

    email: str

    expectedAmount: typing.Union[int, float]

    fee: typing.Union[int, float]

    feeBearer: str

    fullname: str

    id: str

    memo: str

    merchant: str

    # This is defined only if the voucher payment has been received
    paidAt: datetime

    paymentStatus: str

    # This is defined only if the voucher has been paid and redeemed
    rate: typing.Union[int, float]

    # This is defined only if the voucher was created using a valid rate key
    rateKey: str

    # This is defined only if the voucher payment has been received
    receivedAmount: typing.Union[int, float]

    # This is defined only if the voucher payment has been received
    voucherCode: str

class VoucherGetMultipleRecordsResponseDataItem(RequiredVoucherGetMultipleRecordsResponseDataItem, OptionalVoucherGetMultipleRecordsResponseDataItem):
    pass
