# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVoucherGetRecordResponseDataItem(TypedDict):
    pass

class OptionalVoucherGetRecordResponseDataItem(TypedDict, total=False):
    # Type of created bank account. Note that this property is only available in v2.
    accountType: str

    amount: typing.Union[int, float]

    # This property is optional. Only available if the voucher has been cancelled.
    cancelledAt: datetime

    createdAt: str

    currency: str

    # Timestamp of when the voucher was redeemed. If voucher has not been redeemed, this field is undefined.
    dateRedeemed: datetime

    email: str

    fee: typing.Union[int, float]

    feeBearer: str

    fullname: str

    id: str

    memo: str

    merchant: str

    paymentExpiresAt: datetime

    paymentStatus: str

    # Voucher code. Present only if voucher has been paid
    voucherCode: str

class VoucherGetRecordResponseDataItem(RequiredVoucherGetRecordResponseDataItem, OptionalVoucherGetRecordResponseDataItem):
    pass
