# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVoucherRedeemExistingUnusedRequest(TypedDict):
    # Email that was used to create the voucher
    email: str

    # Voucher code to be redeemed
    voucherCode: str

class OptionalVoucherRedeemExistingUnusedRequest(TypedDict, total=False):
    pass

class VoucherRedeemExistingUnusedRequest(RequiredVoucherRedeemExistingUnusedRequest, OptionalVoucherRedeemExistingUnusedRequest):
    pass
