# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_redeem_and_withdraw400_response_errors import VoucherRedeemAndWithdraw400ResponseErrors

class RequiredVoucherRedeemAndWithdraw400Response(TypedDict):
    pass

class OptionalVoucherRedeemAndWithdraw400Response(TypedDict, total=False):
    errors: VoucherRedeemAndWithdraw400ResponseErrors

    message: str

    success: bool

class VoucherRedeemAndWithdraw400Response(RequiredVoucherRedeemAndWithdraw400Response, OptionalVoucherRedeemAndWithdraw400Response):
    pass
