# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_redeem_and_withdraw_response_data import VoucherRedeemAndWithdrawResponseData

class RequiredVoucherRedeemAndWithdrawResponse(TypedDict):
    pass

class OptionalVoucherRedeemAndWithdrawResponse(TypedDict, total=False):
    data: VoucherRedeemAndWithdrawResponseData

    message: str

    success: bool

class VoucherRedeemAndWithdrawResponse(RequiredVoucherRedeemAndWithdrawResponse, OptionalVoucherRedeemAndWithdrawResponse):
    pass
