# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_redeem_existing_unused404_response_errors import VoucherRedeemExistingUnused404ResponseErrors

class RequiredVoucherRedeemExistingUnused404Response(TypedDict):
    pass

class OptionalVoucherRedeemExistingUnused404Response(TypedDict, total=False):
    errors: VoucherRedeemExistingUnused404ResponseErrors

    message: str

    success: bool

class VoucherRedeemExistingUnused404Response(RequiredVoucherRedeemExistingUnused404Response, OptionalVoucherRedeemExistingUnused404Response):
    pass
