# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_redeem_and_withdraw404_response_errors import VoucherRedeemAndWithdraw404ResponseErrors

class RequiredVoucherRedeemAndWithdraw404Response(TypedDict):
    pass

class OptionalVoucherRedeemAndWithdraw404Response(TypedDict, total=False):
    errors: VoucherRedeemAndWithdraw404ResponseErrors

    message: str

    success: bool

class VoucherRedeemAndWithdraw404Response(RequiredVoucherRedeemAndWithdraw404Response, OptionalVoucherRedeemAndWithdraw404Response):
    pass
