# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.voucher_get_multiple_records_response_data import VoucherGetMultipleRecordsResponseData
from partna_python_sdk.type.voucher_get_multiple_records_response_meta import VoucherGetMultipleRecordsResponseMeta

class RequiredVoucherGetMultipleRecordsResponse(TypedDict):
    pass

class OptionalVoucherGetMultipleRecordsResponse(TypedDict, total=False):
    data: VoucherGetMultipleRecordsResponseData

    message: str

    meta: VoucherGetMultipleRecordsResponseMeta

    success: bool

class VoucherGetMultipleRecordsResponse(RequiredVoucherGetMultipleRecordsResponse, OptionalVoucherGetMultipleRecordsResponse):
    pass
