# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.wallet_get_addresses_response_wallet_addresses import WalletGetAddressesResponseWalletAddresses

class RequiredWalletGetAddressesResponseWallet(TypedDict):
    pass

class OptionalWalletGetAddressesResponseWallet(TypedDict, total=False):
    version: str

    addresses: WalletGetAddressesResponseWalletAddresses

    appName: str

    createdAt: typing.Union[int, float]

    reference: str

    status: str

    uid: str

    updatedAt: typing.Union[int, float]

class WalletGetAddressesResponseWallet(RequiredWalletGetAddressesResponseWallet, OptionalWalletGetAddressesResponseWallet):
    pass
