# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.wallet_get_addresses_response_wallet import WalletGetAddressesResponseWallet

class RequiredWalletGetAddressesResponse(TypedDict):
    pass

class OptionalWalletGetAddressesResponse(TypedDict, total=False):
    message: str

    success: bool

    wallet: WalletGetAddressesResponseWallet

class WalletGetAddressesResponse(RequiredWalletGetAddressesResponse, OptionalWalletGetAddressesResponse):
    pass
