# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWalletExecuteTransferResponseDataTransferDetail(TypedDict):
    pass

class OptionalWalletExecuteTransferResponseDataTransferDetail(TypedDict, total=False):
    address: str

    amount: typing.Union[int, float]

    date: str

    fromCurrency: str

    memo: str

    receiveAmount: typing.Union[int, float]

    sender: str

    status: str

    toCurrency: str

    transactionId: str

    type: str

    username: str

class WalletExecuteTransferResponseDataTransferDetail(RequiredWalletExecuteTransferResponseDataTransferDetail, OptionalWalletExecuteTransferResponseDataTransferDetail):
    pass
