# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from partna_python_sdk.type.wallet_get_supported_config_response_data import WalletGetSupportedConfigResponseData

class RequiredWalletGetSupportedConfigResponse(TypedDict):
    pass

class OptionalWalletGetSupportedConfigResponse(TypedDict, total=False):
    data: WalletGetSupportedConfigResponseData

    message: str

    state: bool

class WalletGetSupportedConfigResponse(RequiredWalletGetSupportedConfigResponse, OptionalWalletGetSupportedConfigResponse):
    pass
