# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebhookGetCallbackUrlResponseData(TypedDict):
    pass

class OptionalWebhookGetCallbackUrlResponseData(TypedDict, total=False):
    # The callback url. e.g. https://www.example.com/callback
    callbackUrl: str

class WebhookGetCallbackUrlResponseData(RequiredWebhookGetCallbackUrlResponseData, OptionalWebhookGetCallbackUrlResponseData):
    pass
