# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from partna_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from partna_python_sdk.api_response import AsyncGeneratorResponse
from partna_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from partna_python_sdk import schemas  # noqa: F401

from partna_python_sdk.model.payment_create_new_payment_request import PaymentCreateNewPaymentRequest as PaymentCreateNewPaymentRequestSchema
from partna_python_sdk.model.payment_create_new_payment_response import PaymentCreateNewPaymentResponse as PaymentCreateNewPaymentResponseSchema

from partna_python_sdk.type.payment_create_new_payment_request import PaymentCreateNewPaymentRequest
from partna_python_sdk.type.payment_create_new_payment_response import PaymentCreateNewPaymentResponse

from ...api_client import Dictionary
from partna_python_sdk.pydantic.payment_create_new_payment_request import PaymentCreateNewPaymentRequest as PaymentCreateNewPaymentRequestPydantic
from partna_python_sdk.pydantic.payment_create_new_payment_response import PaymentCreateNewPaymentResponse as PaymentCreateNewPaymentResponsePydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = PaymentCreateNewPaymentRequestSchema


request_body_payment_create_new_payment_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'ApiKey',
    'ApiUser',
    'UserVersion',
]
SchemaFor200ResponseBodyApplicationJson = PaymentCreateNewPaymentResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PaymentCreateNewPaymentResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PaymentCreateNewPaymentResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_new_payment_mapped_args(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if account_name is not None:
            _body["accountName"] = account_name
        if account_number is not None:
            _body["accountNumber"] = account_number
        if bank is not None:
            _body["bank"] = bank
        if bank_code is not None:
            _body["bankCode"] = bank_code
        if business_id is not None:
            _body["businessId"] = business_id
        if coinprofile_username is not None:
            _body["coinprofileUsername"] = coinprofile_username
        if country is not None:
            _body["country"] = country
        if customer_email is not None:
            _body["customerEmail"] = customer_email
        if incoming_amount is not None:
            _body["incomingAmount"] = incoming_amount
        if incoming_currency is not None:
            _body["incomingCurrency"] = incoming_currency
        if outgoing_amount is not None:
            _body["outgoingAmount"] = outgoing_amount
        if outgoing_currency is not None:
            _body["outgoingCurrency"] = outgoing_currency
        if payment_type is not None:
            _body["paymentType"] = payment_type
        if rate_key is not None:
            _body["rateKey"] = rate_key
        if reference is not None:
            _body["reference"] = reference
        args.body = _body
        return args

    async def _acreate_new_payment_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create payment
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payment',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_payment_create_new_payment_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_new_payment_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create payment
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payment',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_payment_create_new_payment_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateNewPaymentRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_new_payment(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_payment_mapped_args(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
        )
        return await self._acreate_new_payment_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_new_payment(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_payment_mapped_args(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
        )
        return self._create_new_payment_oapg(
            body=args.body,
        )

class CreateNewPayment(BaseApi):

    async def acreate_new_payment(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> PaymentCreateNewPaymentResponsePydantic:
        raw_response = await self.raw.acreate_new_payment(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
            **kwargs,
        )
        if validate:
            return PaymentCreateNewPaymentResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PaymentCreateNewPaymentResponsePydantic, raw_response.body)
    
    
    def create_new_payment(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
        validate: bool = False,
    ) -> PaymentCreateNewPaymentResponsePydantic:
        raw_response = self.raw.create_new_payment(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
        )
        if validate:
            return PaymentCreateNewPaymentResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(PaymentCreateNewPaymentResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_payment_mapped_args(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
        )
        return await self._acreate_new_payment_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        business_id: str,
        customer_email: str,
        incoming_currency: str,
        outgoing_currency: str,
        payment_type: str,
        account_name: typing.Optional[str] = None,
        account_number: typing.Optional[str] = None,
        bank: typing.Optional[str] = None,
        bank_code: typing.Optional[str] = None,
        coinprofile_username: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        incoming_amount: typing.Optional[typing.Union[int, float]] = None,
        outgoing_amount: typing.Optional[typing.Union[int, float]] = None,
        rate_key: typing.Optional[str] = None,
        reference: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_payment_mapped_args(
            business_id=business_id,
            customer_email=customer_email,
            incoming_currency=incoming_currency,
            outgoing_currency=outgoing_currency,
            payment_type=payment_type,
            account_name=account_name,
            account_number=account_number,
            bank=bank,
            bank_code=bank_code,
            coinprofile_username=coinprofile_username,
            country=country,
            incoming_amount=incoming_amount,
            outgoing_amount=outgoing_amount,
            rate_key=rate_key,
            reference=reference,
        )
        return self._create_new_payment_oapg(
            body=args.body,
        )

