# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BalanceGetAccountBalance200ResponseDataBalances(BaseModel):
    # User's balance amount
    amount: typing.Optional[int] = Field(None, alias='amount')

    formatted_amount: typing.Optional[int] = Field(None, alias='formattedAmount')

    to_currency: typing.Optional[str] = Field(None, alias='toCurrency')

    total_recieved: typing.Optional[int] = Field(None, alias='totalRecieved')

    total_sent: typing.Optional[int] = Field(None, alias='totalSent')

    txn_count: typing.Optional[typing.Union[int, float]] = Field(None, alias='txnCount')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
