# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BalanceTransferFundsRequest(BaseModel):
    # Currency being sent.
    currency: Literal["NGN", "USD"] = Field(alias='currency')

    # Receiver's coinprofile username.
    receiver_username: str = Field(alias='receiverUsername')

    # Amount to transfer.
    amount: typing.Optional[str] = Field(None, alias='amount')

    # Transaction memo.
    memo: typing.Optional[str] = Field(None, alias='memo')

    # The type of OTP to be used.
    otp_type: typing.Optional[Literal["otp", "totp"]] = Field(None, alias='otpType')

    # The token to be used for OTP.
    token: typing.Optional[str] = Field(None, alias='token')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
