# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class MerchantsGetRecordResponseData(BaseModel):
    # Merchant's credit currency
    credit_currency: typing.Optional[Literal["NGN", "USD"]] = Field(None, alias='creditCurrency')

    # Merchant email address
    email: typing.Optional[str] = Field(None, alias='email')

    # API key expiry date and time
    expires: typing.Optional[datetime] = Field(None, alias='expires')

    # Merchant logo URL
    logo: typing.Optional[str] = Field(None, alias='logo')

    # Merchant username
    username: typing.Optional[str] = Field(None, alias='username')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
