# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.rates_get_conversion_rates_response_data_usdngn import RatesGetConversionRatesResponseDataUsdngn

class RatesGetConversionRatesResponseData(BaseModel):
    u_s_d_n_g_n: typing.Optional[RatesGetConversionRatesResponseDataUsdngn] = Field(None, alias='USDNGN')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
