# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class RatesGetCurrentRatesResponseDataYourCurrency(BaseModel):
    key: typing.Optional[str] = Field(None, alias='key')

    rate: typing.Optional[typing.Union[int, float]] = Field(None, alias='rate')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
