# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.rates_get_current_rates_response_data_your_currency import RatesGetCurrentRatesResponseDataYourCurrency

class RatesGetCurrentRatesResponseData(BaseModel):
    y_o_u_r__c_u_r_r_e_n_c_y: typing.Optional[RatesGetCurrentRatesResponseDataYourCurrency] = Field(None, alias='YOUR_CURRENCY')

    public_key: typing.Optional[str] = Field(None, alias='publicKey')

    signature: typing.Optional[str] = Field(None, alias='signature')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
