# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.transaction_get_user_transaction_summary_response_data_txn_data import TransactionGetUserTransactionSummaryResponseDataTxnData

class TransactionGetUserTransactionSummaryResponseDataTxn(BaseModel):
    data: typing.Optional[TransactionGetUserTransactionSummaryResponseDataTxnData] = Field(None, alias='data')

    page: typing.Optional[typing.Union[int, float]] = Field(None, alias='page')

    pages: typing.Optional[typing.Union[int, float]] = Field(None, alias='pages')

    per_page: typing.Optional[typing.Union[int, float]] = Field(None, alias='perPage')

    total: typing.Optional[typing.Union[int, float]] = Field(None, alias='total')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
