# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.transaction_get_user_transaction_summary_response_data_txn_data_item import TransactionGetUserTransactionSummaryResponseDataTxnDataItem

TransactionGetUserTransactionSummaryResponseDataTxnData = typing.List[TransactionGetUserTransactionSummaryResponseDataTxnDataItem]
