# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.transaction_get_user_transaction_summary_response_data_summary import TransactionGetUserTransactionSummaryResponseDataSummary
from partna_python_sdk.pydantic.transaction_get_user_transaction_summary_response_data_txn import TransactionGetUserTransactionSummaryResponseDataTxn

class TransactionGetUserTransactionSummaryResponseData(BaseModel):
    summary: typing.Optional[TransactionGetUserTransactionSummaryResponseDataSummary] = Field(None, alias='summary')

    txn: typing.Optional[TransactionGetUserTransactionSummaryResponseDataTxn] = Field(None, alias='txn')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
