# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class VoucherGetMultipleRecordsResponseDataItem(BaseModel):
    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    created_at: typing.Optional[datetime] = Field(None, alias='createdAt')

    currency: typing.Optional[str] = Field(None, alias='currency')

    # This is defined only if the voucher payment has been received
    date_redeemed: typing.Optional[datetime] = Field(None, alias='dateRedeemed')

    email: typing.Optional[str] = Field(None, alias='email')

    expected_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='expectedAmount')

    fee: typing.Optional[typing.Union[int, float]] = Field(None, alias='fee')

    fee_bearer: typing.Optional[Literal["client", "merchant"]] = Field(None, alias='feeBearer')

    fullname: typing.Optional[str] = Field(None, alias='fullname')

    id: typing.Optional[str] = Field(None, alias='id')

    memo: typing.Optional[str] = Field(None, alias='memo')

    merchant: typing.Optional[str] = Field(None, alias='merchant')

    # This is defined only if the voucher payment has been received
    paid_at: typing.Optional[datetime] = Field(None, alias='paidAt')

    payment_status: typing.Optional[Literal["paid", "unpaid"]] = Field(None, alias='paymentStatus')

    # This is defined only if the voucher has been paid and redeemed
    rate: typing.Optional[typing.Union[int, float]] = Field(None, alias='rate')

    # This is defined only if the voucher was created using a valid rate key
    rate_key: typing.Optional[str] = Field(None, alias='rateKey')

    # This is defined only if the voucher payment has been received
    received_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='receivedAmount')

    # This is defined only if the voucher payment has been received
    voucher_code: typing.Optional[str] = Field(None, alias='voucherCode')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
