# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.voucher_minmax_amount_get_min_max_amount_response_data_ngn import VoucherMinmaxAmountGetMinMaxAmountResponseDataNgn
from partna_python_sdk.pydantic.voucher_minmax_amount_get_min_max_amount_response_data_usd import VoucherMinmaxAmountGetMinMaxAmountResponseDataUsd

class VoucherMinmaxAmountGetMinMaxAmountResponseData(BaseModel):
    n_g_n: typing.Optional[VoucherMinmaxAmountGetMinMaxAmountResponseDataNgn] = Field(None, alias='NGN')

    u_s_d: typing.Optional[VoucherMinmaxAmountGetMinMaxAmountResponseDataUsd] = Field(None, alias='USD')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
