# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from partna_python_sdk.pydantic.wallet_execute_transfer_response_data_transfer_detail import WalletExecuteTransferResponseDataTransferDetail

class WalletExecuteTransferResponseData(BaseModel):
    transfer_detail: typing.Optional[WalletExecuteTransferResponseDataTransferDetail] = Field(None, alias='transferDetail')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
