# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class WalletExecuteTransferResponseDataTransferDetail(BaseModel):
    address: typing.Optional[str] = Field(None, alias='address')

    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    date: typing.Optional[str] = Field(None, alias='date')

    from_currency: typing.Optional[str] = Field(None, alias='fromCurrency')

    memo: typing.Optional[str] = Field(None, alias='memo')

    receive_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='receiveAmount')

    sender: typing.Optional[str] = Field(None, alias='sender')

    status: typing.Optional[str] = Field(None, alias='status')

    to_currency: typing.Optional[str] = Field(None, alias='toCurrency')

    transaction_id: typing.Optional[str] = Field(None, alias='transactionId')

    type: typing.Optional[str] = Field(None, alias='type')

    username: typing.Optional[str] = Field(None, alias='username')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
