# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class WalletExecuteTransferRequest(BaseModel):
    # Wallet address to transfer crypto
    address: str = Field(alias='address')

    # Amount of crypto to be transferred
    amount: typing.Union[int, float] = Field(alias='amount')

    # Currency of the crypto to be transferred
    currency: str = Field(alias='currency')

    # Network on which crypto is to be transferred
    network: str = Field(alias='network')

    # Optional transaction memo
    memo: typing.Optional[str] = Field(None, alias='memo')

    # Wallet type
    wallet_type: typing.Optional[str] = Field(None, alias='walletType')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
