# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.auth_api_key.post import GenerateNewApiKey
from partna_python_sdk.apis.tags.api_key_api_raw import ApiKeyApiRaw


class ApiKeyApi(
    GenerateNewApiKey,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApiKeyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApiKeyApiRaw(api_client)
