# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_balance.get import GetAccountBalance
from partna_python_sdk.paths.balance.get import GetAccountBalance0
from partna_python_sdk.paths.balance_transfer.post import TransferFunds
from partna_python_sdk.paths.balance_withdraw.post import WithdrawFunds
from partna_python_sdk.apis.tags.balance_api_raw import BalanceApiRaw


class BalanceApi(
    GetAccountBalance,
    GetAccountBalance0,
    TransferFunds,
    WithdrawFunds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BalanceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BalanceApiRaw(api_client)
