# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.bank_supported.get import GetSupportedBanks
from partna_python_sdk.apis.tags.bank_api_raw import BankApiRaw


class BankApi(
    GetSupportedBanks,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BankApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BankApiRaw(api_client)
