# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.currency_minimum_allowed.get import GetMinimumAllowed
from partna_python_sdk.paths.currency_supported.get import ListSupportedCurrencies
from partna_python_sdk.apis.tags.currency_api_raw import CurrencyApiRaw


class CurrencyApi(
    GetMinimumAllowed,
    ListSupportedCurrencies,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CurrencyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CurrencyApiRaw(api_client)
