# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.currency_minimum_allowed.get import GetMinimumAllowedRaw
from partna_python_sdk.paths.currency_supported.get import ListSupportedCurrenciesRaw


class CurrencyApiRaw(
    GetMinimumAllowedRaw,
    ListSupportedCurrenciesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
