# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_merchants.get import GetRecordRaw
from partna_python_sdk.paths.v1_merchants.patch import UpdateRecordRaw


class MerchantsApiRaw(
    GetRecordRaw,
    UpdateRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
