# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.payment.post import CreateNewPaymentRaw
from partna_python_sdk.paths.payment_payment_id.get import GetSingleRaw
from partna_python_sdk.paths.payment_resolve.get import ResolveOverpaidTransactionRaw


class PaymentApiRaw(
    CreateNewPaymentRaw,
    GetSingleRaw,
    ResolveOverpaidTransactionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
