# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.payment.post import CreateNewPayment
from partna_python_sdk.paths.payment_payment_id.get import GetSingle
from partna_python_sdk.paths.payment_resolve.get import ResolveOverpaidTransaction
from partna_python_sdk.apis.tags.payment_api_raw import PaymentApiRaw


class PaymentApi(
    CreateNewPayment,
    GetSingle,
    ResolveOverpaidTransaction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentApiRaw(api_client)
