# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_currency_rates.get import GetConversionRates
from partna_python_sdk.paths.currency_rate.get import GetCurrentRates
from partna_python_sdk.apis.tags.rates_api_raw import RatesApiRaw


class RatesApi(
    GetConversionRates,
    GetCurrentRates,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RatesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RatesApiRaw(api_client)
