# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_currency_rates.get import GetConversionRatesRaw
from partna_python_sdk.paths.currency_rate.get import GetCurrentRatesRaw


class RatesApiRaw(
    GetConversionRatesRaw,
    GetCurrentRatesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
