# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.transaction_transaction_id.get import GetDetailsRaw
from partna_python_sdk.paths.transaction_summary.get import GetUserTransactionSummaryRaw
from partna_python_sdk.paths.transaction.get import GetUserTransactionsRaw


class TransactionApiRaw(
    GetDetailsRaw,
    GetUserTransactionSummaryRaw,
    GetUserTransactionsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
