# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_voucher_min_max.get import GetMinMaxAmount
from partna_python_sdk.apis.tags.voucher_min_max_amount_api_raw import VoucherMinMaxAmountApiRaw


class VoucherMinMaxAmountApi(
    GetMinMaxAmount,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoucherMinMaxAmountApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoucherMinMaxAmountApiRaw(api_client)
