# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_vouchers.post import CreatePayment
from partna_python_sdk.paths.v1_voucher_get_many.get import GetMultipleRecords
from partna_python_sdk.paths.v1_vouchers.get import GetRecord
from partna_python_sdk.paths.v1_voucher.patch import RedeemAndWithdraw
from partna_python_sdk.paths.v1_vouchers.patch import RedeemExistingUnused
from partna_python_sdk.apis.tags.voucher_api_raw import VoucherApiRaw


class VoucherApi(
    CreatePayment,
    GetMultipleRecords,
    GetRecord,
    RedeemAndWithdraw,
    RedeemExistingUnused,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoucherApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoucherApiRaw(api_client)
