# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.v1_voucher_fee.get import GetFee
from partna_python_sdk.apis.tags.voucher_fee_api_raw import VoucherFeeApiRaw


class VoucherFeeApi(
    GetFee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VoucherFeeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VoucherFeeApiRaw(api_client)
