# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.wallet_transfer.post import ExecuteTransferRaw
from partna_python_sdk.paths.wallet.get import GetAddressesRaw
from partna_python_sdk.paths.wallet_supported_config.get import GetSupportedConfigRaw


class WalletApiRaw(
    ExecuteTransferRaw,
    GetAddressesRaw,
    GetSupportedConfigRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
