# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.callbackurl.get import GetCallbackUrlRaw
from partna_python_sdk.paths.callbackurl.put import SubscribeWebhookCallbackRaw


class WebhookApiRaw(
    GetCallbackUrlRaw,
    SubscribeWebhookCallbackRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
