# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from partna_python_sdk.paths.callbackurl.get import GetCallbackUrl
from partna_python_sdk.paths.callbackurl.put import SubscribeWebhookCallback
from partna_python_sdk.apis.tags.webhook_api_raw import WebhookApiRaw


class WebhookApi(
    GetCallbackUrl,
    SubscribeWebhookCallback,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhookApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhookApiRaw(api_client)
