# coding: utf-8

# flake8: noqa

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from partna_python_sdk.api_client import ApiClient

# import Configuration
from partna_python_sdk.configuration import Configuration

# import exceptions
from partna_python_sdk.exceptions import OpenApiException
from partna_python_sdk.exceptions import ApiAttributeError
from partna_python_sdk.exceptions import ApiTypeError
from partna_python_sdk.exceptions import ApiValueError
from partna_python_sdk.exceptions import ApiKeyError
from partna_python_sdk.exceptions import ApiException

from partna_python_sdk.client import Partna
