# coding: utf-8
"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from partna_python_sdk.client_custom import ClientCustom
from partna_python_sdk.configuration import Configuration
from partna_python_sdk.api_client import ApiClient
from partna_python_sdk.type_util import copy_signature
from partna_python_sdk.apis.tags.api_key_api import ApiKeyApi
from partna_python_sdk.apis.tags.balance_api import BalanceApi
from partna_python_sdk.apis.tags.bank_api import BankApi
from partna_python_sdk.apis.tags.bank_account_api import BankAccountApi
from partna_python_sdk.apis.tags.currency_api import CurrencyApi
from partna_python_sdk.apis.tags.merchants_api import MerchantsApi
from partna_python_sdk.apis.tags.mock_payment_api import MockPaymentApi
from partna_python_sdk.apis.tags.payment_api import PaymentApi
from partna_python_sdk.apis.tags.rates_api import RatesApi
from partna_python_sdk.apis.tags.transaction_api import TransactionApi
from partna_python_sdk.apis.tags.transactions_api import TransactionsApi
from partna_python_sdk.apis.tags.voucher_api import VoucherApi
from partna_python_sdk.apis.tags.voucher_fee_api import VoucherFeeApi
from partna_python_sdk.apis.tags.voucher_min_max_amount_api import VoucherMinMaxAmountApi
from partna_python_sdk.apis.tags.wallet_api import WalletApi
from partna_python_sdk.apis.tags.webhook_api import WebhookApi



class Partna(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.api_key: ApiKeyApi = ApiKeyApi(api_client)
        self.balance: BalanceApi = BalanceApi(api_client)
        self.bank: BankApi = BankApi(api_client)
        self.bank_account: BankAccountApi = BankAccountApi(api_client)
        self.currency: CurrencyApi = CurrencyApi(api_client)
        self.merchants: MerchantsApi = MerchantsApi(api_client)
        self.mock_payment: MockPaymentApi = MockPaymentApi(api_client)
        self.payment: PaymentApi = PaymentApi(api_client)
        self.rates: RatesApi = RatesApi(api_client)
        self.transaction: TransactionApi = TransactionApi(api_client)
        self.transactions: TransactionsApi = TransactionsApi(api_client)
        self.voucher: VoucherApi = VoucherApi(api_client)
        self.voucher_fee: VoucherFeeApi = VoucherFeeApi(api_client)
        self.voucher_min_max_amount: VoucherMinMaxAmountApi = VoucherMinMaxAmountApi(api_client)
        self.wallet: WalletApi = WalletApi(api_client)
        self.webhook: WebhookApi = WebhookApi(api_client)
