# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from partna_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from partna_python_sdk.api_response import AsyncGeneratorResponse
from partna_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from partna_python_sdk import schemas  # noqa: F401

from partna_python_sdk.model.wallet_execute_transfer_request import WalletExecuteTransferRequest as WalletExecuteTransferRequestSchema
from partna_python_sdk.model.wallet_execute_transfer_response import WalletExecuteTransferResponse as WalletExecuteTransferResponseSchema

from partna_python_sdk.type.wallet_execute_transfer_request import WalletExecuteTransferRequest
from partna_python_sdk.type.wallet_execute_transfer_response import WalletExecuteTransferResponse

from ...api_client import Dictionary
from partna_python_sdk.pydantic.wallet_execute_transfer_response import WalletExecuteTransferResponse as WalletExecuteTransferResponsePydantic
from partna_python_sdk.pydantic.wallet_execute_transfer_request import WalletExecuteTransferRequest as WalletExecuteTransferRequestPydantic

# body param
SchemaForRequestBodyApplicationJson = WalletExecuteTransferRequestSchema


request_body_wallet_execute_transfer_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = WalletExecuteTransferResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: WalletExecuteTransferResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: WalletExecuteTransferResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _execute_transfer_mapped_args(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if address is not None:
            _body["address"] = address
        if amount is not None:
            _body["amount"] = amount
        if currency is not None:
            _body["currency"] = currency
        if memo is not None:
            _body["memo"] = memo
        if network is not None:
            _body["network"] = network
        if wallet_type is not None:
            _body["walletType"] = wallet_type
        args.body = _body
        return args

    async def _aexecute_transfer_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Wallet transfer
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/wallet/transfer',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_wallet_execute_transfer_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _execute_transfer_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Wallet transfer
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/wallet/transfer',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_wallet_execute_transfer_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ExecuteTransferRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aexecute_transfer(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._execute_transfer_mapped_args(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
        )
        return await self._aexecute_transfer_oapg(
            body=args.body,
            **kwargs,
        )
    
    def execute_transfer(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._execute_transfer_mapped_args(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
        )
        return self._execute_transfer_oapg(
            body=args.body,
        )

class ExecuteTransfer(BaseApi):

    async def aexecute_transfer(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> WalletExecuteTransferResponsePydantic:
        raw_response = await self.raw.aexecute_transfer(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
            **kwargs,
        )
        if validate:
            return WalletExecuteTransferResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(WalletExecuteTransferResponsePydantic, raw_response.body)
    
    
    def execute_transfer(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
        validate: bool = False,
    ) -> WalletExecuteTransferResponsePydantic:
        raw_response = self.raw.execute_transfer(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
        )
        if validate:
            return WalletExecuteTransferResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(WalletExecuteTransferResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._execute_transfer_mapped_args(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
        )
        return await self._aexecute_transfer_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        address: str,
        amount: typing.Union[int, float],
        currency: str,
        network: str,
        memo: typing.Optional[str] = None,
        wallet_type: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._execute_transfer_mapped_args(
            address=address,
            amount=amount,
            currency=currency,
            network=network,
            memo=memo,
            wallet_type=wallet_type,
        )
        return self._execute_transfer_oapg(
            body=args.body,
        )

