# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from partna_python_sdk import schemas  # noqa: F401


class BalanceGetAccountBalance200ResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def balances() -> typing.Type['BalanceGetAccountBalance200ResponseDataBalances']:
                return BalanceGetAccountBalance200ResponseDataBalances
            __annotations__ = {
                "balances": balances,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["balances"]) -> 'BalanceGetAccountBalance200ResponseDataBalances': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["balances", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["balances"]) -> typing.Union['BalanceGetAccountBalance200ResponseDataBalances', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["balances", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        balances: typing.Union['BalanceGetAccountBalance200ResponseDataBalances', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BalanceGetAccountBalance200ResponseData':
        return super().__new__(
            cls,
            *args,
            balances=balances,
            _configuration=_configuration,
            **kwargs,
        )

from partna_python_sdk.model.balance_get_account_balance200_response_data_balances import BalanceGetAccountBalance200ResponseDataBalances
