# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from partna_python_sdk import schemas  # noqa: F401


class TransactionsGetMerchantTransactionSummaryResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            totalPaid = schemas.Int32Schema
            totalRedeemed = schemas.Int32Schema
            totalUnpaid = schemas.Int32Schema
            totalUnredeemed = schemas.Int32Schema
            __annotations__ = {
                "totalPaid": totalPaid,
                "totalRedeemed": totalRedeemed,
                "totalUnpaid": totalUnpaid,
                "totalUnredeemed": totalUnredeemed,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalPaid"]) -> MetaOapg.properties.totalPaid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalRedeemed"]) -> MetaOapg.properties.totalRedeemed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalUnpaid"]) -> MetaOapg.properties.totalUnpaid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalUnredeemed"]) -> MetaOapg.properties.totalUnredeemed: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["totalPaid", "totalRedeemed", "totalUnpaid", "totalUnredeemed", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalPaid"]) -> typing.Union[MetaOapg.properties.totalPaid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalRedeemed"]) -> typing.Union[MetaOapg.properties.totalRedeemed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalUnpaid"]) -> typing.Union[MetaOapg.properties.totalUnpaid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalUnredeemed"]) -> typing.Union[MetaOapg.properties.totalUnredeemed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["totalPaid", "totalRedeemed", "totalUnpaid", "totalUnredeemed", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        totalPaid: typing.Union[MetaOapg.properties.totalPaid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalRedeemed: typing.Union[MetaOapg.properties.totalRedeemed, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalUnpaid: typing.Union[MetaOapg.properties.totalUnpaid, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalUnredeemed: typing.Union[MetaOapg.properties.totalUnredeemed, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionsGetMerchantTransactionSummaryResponseData':
        return super().__new__(
            cls,
            *args,
            totalPaid=totalPaid,
            totalRedeemed=totalRedeemed,
            totalUnpaid=totalUnpaid,
            totalUnredeemed=totalUnredeemed,
            _configuration=_configuration,
            **kwargs,
        )
