# coding: utf-8

"""
    Coinprofile business API

    Coinprofile business API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from partna_python_sdk import schemas  # noqa: F401


class WalletExecuteTransferResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def transferDetail() -> typing.Type['WalletExecuteTransferResponseDataTransferDetail']:
                return WalletExecuteTransferResponseDataTransferDetail
            __annotations__ = {
                "transferDetail": transferDetail,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transferDetail"]) -> 'WalletExecuteTransferResponseDataTransferDetail': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["transferDetail", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transferDetail"]) -> typing.Union['WalletExecuteTransferResponseDataTransferDetail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transferDetail", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        transferDetail: typing.Union['WalletExecuteTransferResponseDataTransferDetail', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WalletExecuteTransferResponseData':
        return super().__new__(
            cls,
            *args,
            transferDetail=transferDetail,
            _configuration=_configuration,
            **kwargs,
        )

from partna_python_sdk.model.wallet_execute_transfer_response_data_transfer_detail import WalletExecuteTransferResponseDataTransferDetail
